spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:spring-security
    username: testdb
    password:
  h2:
    console:
      enabled: true
fileRepo: C:\Users\ciacc\Desktop\FileRepo